---

#  - name: Open firewall ports for app

    # nginx must be build from scratch, with upload module
    #sudo mkdir /opt/httpupload
    #cd /opt/httpupload
    #sudo wget https://github.com/vkholodkov/nginx-upload-module/archive/2.2.zip
    #sudo unzip 2.2.zip

  - name: Install NGINX required system packages
    apt: pkg={{ item }} state=installed update-cache=yes
    with_items: "{{ nginx_packages }}"
    become: true

  - name: Install nginx configuration file.
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify: restart nginx
    become: true

#  - name: Uninstall web server packages
#    apt: pkg=nginx state=removed update-cache=yes
#    when: remove == "true"
#    become: true
