---
- hosts: galaxy-servers
  gather_facts: true
  become: true
  vars_files:
    - group_vars/vars

  roles:
    - provision
    - { role: postgres, when: mode == 'production' }
    - { role: nginx, when: mode == 'production' }
