---
- hosts: galaxy-servers
  gather_facts: true

  vars_files:
    - group_vars/vars

  roles:
     - { role: postgres, when: database_type == 'postgres' }
     - { role: nginx, when: webserver_type == 'nginx' }
     - galaxy
