---
- hosts: pulsar-servers
  gather_facts: true
  vars_files:
    - group_vars/vars
  vars:
    - pulsar_pip_install: true

  tasks:
#   - name: Inastall Mercurial
#     apt: pkg={{ item }} state=installed
#     become: true
#     when: ansible_distribution == 'Ubuntu'
#     with_items:
#      - git
#      - python-virtualenv

#   - name: Install VSC
#     yum: pkg={{ item }} state=installed
#     become: true
#     when: ansible_distribution == 'CentOS'
#     with_items:
#      - git

   - name: enable python2.7 on CentOS
     shell: source /opt/rh/python27/enable && mkdir -p "{{ pulsar_server_dir }}" && cd "{{ pulsar_server_dir }}" && virtualenv venv # && source venv/bin/activate && pip install --user pulsar-app
     #  shell: source /home/username/.bashrc && [the actual command you want run]
     args:
      executable: /bin/bash
     when: ansible_distribution == 'CentOS'

   - name: install && config pulsar-app on CentOS
     shell: cd "{{ pulsar_server_dir }}" && source /opt/rh/python27/enable && source venv/bin/activate && pip install pulsar-app && pulsar-config --force
     args:
      executable: /bin/bash
     when: ansible_distribution == 'CentOS'

#  roles:
#    - role: ansible-pulsar
#


#  source /opt/rh/python27/enable &&
#mkdir pulsar
#cd pulsar
#virtualenv venv
# && source venv/bin/activate && pip install pulsar-app
#

#   - name: enable python2.7 on CentOS
#     shell: source /opt/rh/python27/enable
#     #  shell: source /home/username/.bashrc && [the actual command you want run]
#     args:
#      executable: /bin/bash
#     when: ansible_distribution == 'CentOS'



#   - name: Install Pulsar (pip)
#     pip:
#       name: "{{ 'git+' ~ pulsar_git_repo ~ '@' ~ pulsar_changeset_id ~ '#egg=pulsar' if pulsar_changeset_id is defined else 'pulsar' }}"
#       virtualenv: "{{ pulsar_venv_dir }}"
#       virtualenv_command: "{{ pip_virtualenv_command | default(omit) }}"
#     when: pulsar_pip_install == true


# https://github.com/galaxyproject/ansible-pulsar
# http://stackoverflow.com/questions/22256884/not-possible-to-source-bashrc-with-ansible

#- hosts: localhost
#  gather_facts: true
#  connection: local
#  vars_files:
#    - group_vars/vars
#  vars:
#    pulsar_server_dir: "{{ pulsar_server_dir }}"

#
#  roles:
#    - role: ansible-pulsar

#- hosts: galaxy-servers
#  gather_facts: true
#  become_user: "{{ project_user }}"
#
#  vars_files:
#    - group_vars/vars