---
  - name: Install required system packages
    apt: pkg={{ item }} state=installed update-cache=yes
    with_items: "{{ system_packages }}"

  - name: Install required python packages
    apt: pkg={{ item }} state=installed update-cache=yes
    with_items: "{{ python_packages_system }}"
