---

  - name: system sources update
    raw: apt-get -y update
    when: ansible_distribution == 'Ubuntu'

  - name: install python2.7 Ubuntu
    raw: apt-get -y install python2.7 python-simplejson sudo
    when: ansible_distribution == 'Ubuntu'

  - name: install requirments CentOS
    yum: pkg={{ item }} state=installed
    when: ansible_distribution == 'CentOS'
    with_items: "{{ system_packages_centos }}"

  - name: install python2.7 CentOS
    yum: pkg={{ item }} state=installed
    when: ansible_distribution == 'CentOS'
    with_items: "{{ python_packages_system_centos6 }}"

  - name: Install required system packages
    apt: pkg={{ item }} state=installed update-cache=yes
    when: ansible_distribution == 'Ubuntu'
    with_items: "{{ system_packages }}"

  - name: Install required python packages
    apt: pkg={{ item }} state=installed update-cache=yes
    when: ansible_distribution == 'Ubuntu'
    with_items: "{{ python_packages_system }}"


