---
- hosts: galaxy-servers
  vars_files:
    - ../vars.yml
  remote_user: galaxy

  tasks:

  - name: Start galaxy toolshed daemon
    shell: /bin/bash {{ project_home_dir }}/{{ project_dir }}/run_tool_shed.sh --daemon
