---
- hosts: galaxy-servers
  vars_files:
    - ../vars.yml
  remote_user: galaxy

  tasks:
  - name: Stop galaxy daemon
    shell: /bin/bash {{ project_home_dir }}/{{ project_dir }}/run.sh --stop-daemon
