---

   - name: enable python2.7 on CentOS
     shell: source /opt/rh/python27/enable && mkdir -p "{{ pulsar_server_dir }}" && cd "{{ pulsar_server_dir }}" && virtualenv venv
     #  shell: source /home/username/.bashrc && [the actual command you want run]
     args:
      executable: /bin/bash
     when: ansible_distribution == 'CentOS'

   - name: install && config pulsar-app on CentOS
     shell: cd "{{ pulsar_server_dir }}" && source /opt/rh/python27/enable && source venv/bin/activate && pip install pulsar-app && pulsar-config --force
     args:
      executable: /bin/bash
     when: ansible_distribution == 'CentOS'

   - name: Configure pulsar configs from templates app.yml
     template: src=app.yml.j2 dest={{ pulsar_server_dir }}/app.yml

   - name: Configure pulsar configs from templates server.ini
     template: src=server.ini.j2 dest={{ pulsar_server_dir }}/server.ini

   - name: Configure pulsar configs from templates local_env.sh
     template: src=local_env.sh.j2 dest={{ pulsar_server_dir }}/local_env.sh
