---
  - name: Install web server packages.
    apt: pkg=nginx state=installed update-cache=yes

#  - name: Open firewall ports for app


#  - name: Install web server packages.
#    apt: pkg=nginx state=installed update-cache=yes

    # nginx must be build from scratch, with upload module
    #sudo mkdir /opt/httpupload
    #cd /opt/httpupload
    #sudo wget https://github.com/vkholodkov/nginx-upload-module/archive/2.2.zip
    #sudo unzip 2.2.zip

  - name: Install nginx configuration file.
    copy: src=configs/{{ repo }}/{{ mode }}/nginx/nginx.conf dest=/etc/nginx/
    notify: restart nginx
